sudo: required
services:
  - docker

before_install:
  - cd frontend
  - docker build -t davidodw/frontend -f Dockerfile.dev .

script:
  - docker run davidodw/frontend npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-929917414707"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY