sudo: required
services:
    - docker

before_install:
    - cd fib-calculator
    - docker build -t davidodw/fib-calculator-client-test -f ./client/Dockerfile.dev ./client

script:
    - docker run davidodw/fib-calculator-client-test npm test -- --coverage

after_success:
    - docker build -t davidodw/fib-calculator-client ./client
    - docker build -t davidodw/fib-calculator-nginx ./nginx
    - docker build -t davidodw/fib-calculator-server ./server
    - docker build -t davidodw/fib-calculator-worker ./worker

    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push davidodw/fib-calculator-client
    - docker push davidodw/fib-calculator-nginx
    - docker push davidodw/fib-calculator-server
    - docker push davidodw/fib-calculator-worker

deploy:
    provider: elasticbeanstalk
    region: "ap-southeast-1"
    app: "fib-calculator"
    env: "FibCalculator-env"
    bucket_name: "elasticbeanstalk-ap-southeast-1-929917414707"
    bucket_path: "fib-calculator"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: $AWS_SECRET_KEY
